---
#TODO add fail if this role is not limited to one server
#TODO maybe add run_once to every tasks to avoid a disaster if precedent limitation fails
#For example, if ignore_errors: true is added at playbook level

- name: Stop glusterd on {{ gluster_new_node }}
  service:
    name: glusterd
    state: stopped
  delegate_to: "{{ gluster_new_node }}"

- import_tasks: peers.yml

- name: Start glusterd on {{ gluster_new_node }}
  service:
    name: glusterd
    state: started
  delegate_to: "{{ gluster_new_node }}"

- name: Reset brick
  command: >
    gluster volume reset-brick gv0
    {{ gluster_new_node }}:/data/brick1/gv0
    start
  changed_when: false
